version: '3.3'

services:
  web:
    image: raosuper/microservice
    ports:
     - "80:80"

  words:
    image: raosuper/microservice
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M
